### PR TITLE
MeshFunctions V2

### PR DESCRIPTION
**Pull request by craffael**
This PR introduces the following MeshFunctions and utility functions to operate on them:
- `MeshFunctionFE` represents the solution of a BVP as a mesh function.
- `MeshFunctionGradFE` represents the gradient of a BVP as a mesh function.
- various mesh functions in `mesh_function_binary.h` and `mesh_function_unary.h` which define operator overloads to 
  - add two mesh functions (pointwise)
  - subtract two mesh functions (pointwise)
  - multiply a mesh function by -1 (pointwise)
  - compute squared norm of a scalar/vector valued mesh function (pointwise)
- `IntegrateMeshFunction` which integrates a mesh function over the mesh

In this way, this PR creates an alternative, intuitive way to achieve the following:
- compute error between exact solution and finite element solution (L2 norm or H1 semi-norm)
- compute L2/H1 norm of a finite element solution
- compute L2 norm of an exact analytical solution of a bvp

In this PR, all tests + examples have been adapted to use this new approach. Here is e.g. how the L2/H1 errors in `examples/ellbvp_linfe` is computed (quadrature rules of order 10):
```
// create mesh functions representing solution / gradient of solution
auto mf_sol = lf::uscalfe::MeshFunctionFE(fe_space, sol_vec);
auto mf_grad_sol = lf::uscalfe::MeshFunctionGradFE(fe_space, sol_vec);

double L2err = std::sqrt(IntegrateMeshFunction(mesh, squaredNorm(mf_sol - mf_u), 10));
double H1serr = std::sqrt(lf::uscalfe::IntegrateMeshFunction(mesh, squaredNorm(mf_grad_sol - mf_grad_u), 10));
```

## Advantages of the new approach
- Simpler on a conceptual level because no new concept must be introduced, we can reuse the concept of a mesh function to compute L2/H1 errors. (The current approach needs to introduce the concept of a "LocalComputation" which is rather hard to grasp)
- More flexible, any mesh function can be integrated and mesh functions can be combined to produce new mesh functions. E.g. computing the difference between two BVP solutions is also possible.
- The new approach is faster: on my machine `ellbvp_linfe_demo.cc` takes about 3281 ms to execute with the new approach, the old approach needs 3657 ms (Release mode, average of 4 rounds). I didn't expect this because the new approach doesn't allow us to pre-evaluate the shape functions and doesn't use expression templates. However I managed to do a few eigen specific optimizations (see e.g. mesh_function_binary.h) which seem to be much more important. Similar tricks may be possible with the current/old approach as well but of course I haven't investigated this. 

## Disadvantages of the new approach
- We cannot pre-evaluate shape functions but it seems that this doesn't hurt performance much (see above).

## Outlook
The new approach offers the following exciting possibilities:
1. Extend VtkWriter such that MeshFunctions can be plotted. Using `MeshFunctionFE` or `MeshFunctionGradFE` we can then easily output the (gradient of) bvp solution.
2. Create a `MeshFunctionTransfer` which transfers a mesh function from one mesh level to another mesh level. In this way we could e.g. compute the difference between a fe solution on a coarse mesh and on a fine mesh. Combining this with 1. we could then also visualize second or higher order basis functions/geometry in Paraview by refining the mesh a few times and transferring the fe solution to the fine mesh and visualizing it in Paraview.

## Final remarks
I've tried to document all the new classes/functions as well as possible but I haven't created snippets yet. If we agree to incorporate this change, I will add some snippets to the documentation so it is even easier to understand.

## Edits
- 20.1.2019 20:00 initial timing was wrong: I compared order 10 quadrature rules for error computation (new approach) with order 2 quadrature rules (old approach). It seems that now the new approach is even fast than the old one :)
- 20.1.2019 20:15 Extended Final remarks

### CODE REVIEW

**Comment by craffael** [comment]
I'm glad to hear this :) I unfortuantely don't have a lot of time until thursday to improve the documentation, but I will do it asap and then merge this back into master.

**Comment by hiptmair** [comment]
I have to be careful, because I am receiving complaints by the students that the `lf::uscalfe` level of LehrFEM++ is much too complicated already. They struggled with the need to pass coefficients wrapped into MeshFunctions to ELEMENT_MATRIX_PROVIDER types. What they understand is loops over cells and local quadrature rules.

I propose not to touch the old example, but to introduce a new one, demonstrating the same computations with the use of `MeshFunctionFE`. Actually, in the new example a much simpler problem could be solved (plain homogeneous Neumann problem for the negative Laplacian on a square).

**Comment by hiptmair** [comment]
Please add the new functionality, but leave all current classes and examples unchanged.

**Comment by craffael** [comment]
That's a good idea, I will do undo some of the changes so that we don't break existing functionality.

**Pull request merged**
