### PR TITLE
Lecturecodes

### PR DESCRIPTION
**Pull request by hiptmair**
Codes for course documents. 

Unfortunately also many small changes to different parts of the library. 

Please merge as soon as possible so that links in the lecture document work.

### CODE REVIEW

**Comment by hiptmair** [comment]
clang-tidy problems have  to be fixed.

**Comment by craffael** [comment]
Please note that on line 102 of quad_rule.h the comment now states 
```
@note the _degree_ of a quadrature rule is the degree of exactness + 1,
* because it predicts the order of algebraic covergence of the quadrature
* error when the rule is applied to a smooth integrand.
```
 I think this is outdated/wrong? Did you mean to write `the _order_ of a quadrature rule is the degree of exactness + 1`?

**Comment by hiptmair** [comment]
Update: Fixed/extended a few comments

**Comment by hiptmair** [comment]
NOLINT comments in codes for the lecture are ok. The students should see authentic codes and best practices.

**Comment by hiptmair** [comment]
All tests work, all examples work. In order to speed up the deployment of LehrFEM++ for the course I have merged 'lectvurecodes' into 'master'.

**Pull request merged**
