### PR TITLE
FisherKPP

### PR DESCRIPTION
**Pull request by amloher**

### CODE REVIEW

**Comment by hiptmair** [comment]
Another compilation problem persists:
~~~
FisherKPP $ make
[ 77%] Linking CXX executable splitting
/usr/bin/ld: CMakeFiles/splitting.dir/strangsplitting.cc.o: in function `FisherKPP::StrangSplit::diffusionEvolutionOperator(double, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)':
strangsplitting.cc:(.text+0x0): multiple definition of `FisherKPP::StrangSplit::diffusionEvolutionOperator(double, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)'; CMakeFiles/splitting.dir/strangsplitting_main.cc.o:strangsplitting_main.cc:(.text+0x0): first defined here
/usr/bin/ld: CMakeFiles/splitting.dir/strangsplitting.cc.o: in function `FisherKPP::StrangSplit::Evolution(Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)':
strangsplitting.cc:(.text+0xa80): multiple definition of `FisherKPP::StrangSplit::Evolution(Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)'; CMakeFiles/splitting.dir/strangsplitting_main.cc.o:strangsplitting_main.cc:(.text+0xa80): first defined here
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [projects/FisherKPP/CMakeFiles/splitting.dir/build.make:145: projects/FisherKPP/splitting] Error 1
make[1]: *** [CMakeFiles/Makefile2:4339: projects/FisherKPP/CMakeFiles/splitting.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
~~~

**Comment by amloher** [comment]
> Another compilation problem persists:
> 
> ```
> FisherKPP $ make
> [ 77%] Linking CXX executable splitting
> /usr/bin/ld: CMakeFiles/splitting.dir/strangsplitting.cc.o: in function `FisherKPP::StrangSplit::diffusionEvolutionOperator(double, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)':
> strangsplitting.cc:(.text+0x0): multiple definition of `FisherKPP::StrangSplit::diffusionEvolutionOperator(double, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)'; CMakeFiles/splitting.dir/strangsplitting_main.cc.o:strangsplitting_main.cc:(.text+0x0): first defined here
> /usr/bin/ld: CMakeFiles/splitting.dir/strangsplitting.cc.o: in function `FisherKPP::StrangSplit::Evolution(Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)':
> strangsplitting.cc:(.text+0xa80): multiple definition of `FisherKPP::StrangSplit::Evolution(Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1> const&)'; CMakeFiles/splitting.dir/strangsplitting_main.cc.o:strangsplitting_main.cc:(.text+0xa80): first defined here
> clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [projects/FisherKPP/CMakeFiles/splitting.dir/build.make:145: projects/FisherKPP/splitting] Error 1
> make[1]: *** [CMakeFiles/Makefile2:4339: projects/FisherKPP/CMakeFiles/splitting.dir/all] Error 2
> make: *** [Makefile:161: all] Error 2
> ```

Does this compilation error still persist? I do not get the same error message, but I have had another compilation error, which I have resolved now.

**Comment by hiptmair** [comment]
Fixed problems:

- All templated classes/functions should be implemented in header files .h
- .cc files must not be included, only .h files.

**Comment by craffael** [comment]
Great, now everything seems to compile. I will look at the code in a bit more detail over the weekend...

**Comment by hiptmair** [comment]
AppVeryor build reports strange errors:
~~~
[00:14:59]     69>C:\projects\lehrfempp\projects\FisherKPP\strangsplitting_main.cc(381,63): error C2668: 'lf::mesh::utils::make_CodimMeshDataSet': ambiguous call to overloaded function [C:\projects\lehrfempp\Build\projects\FisherKPP\splitting.vcxproj]
[00:14:59]        C:\projects\lehrfempp\lib\lf\mesh\utils\codim_mesh_data_set.h(95,47): message : could be 'std::shared_ptr<lf::mesh::utils::CodimMeshDataSet<double>> lf::mesh::utils::make_CodimMeshDataSet<double>(std::shared_ptr<const lf::mesh::Mesh>,lf::base::dim_t)' [C:\projects\lehrfempp\Build\projects\FisherKPP\splitting.vcxproj]
[00:14:59]        C:\projects\lehrfempp\lib\lf\mesh\utils\codim_mesh_data_set.h(113,38): message : or       'std::shared_ptr<lf::mesh::utils::CodimMeshDataSet<double>> lf::mesh::utils::make_CodimMeshDataSet<double>(const std::shared_ptr<const lf::mesh::Mesh> &,lf::base::dim_t)' [C:\projects\lehrfempp\Build\projects\FisherKPP\splitting.vcxproj]
~~~
and
~~~
[00:14:59]     69>C:\projects\lehrfempp\projects\FisherKPP\strangsplitting_main.cc(381,63): error C2668: 'lf::mesh::utils::make_CodimMeshDataSet': ambiguous call to overloaded function [C:\projects\lehrfempp\Build\projects\FisherKPP\splitting.vcxproj]
[00:14:59]        C:\projects\lehrfempp\lib\lf\mesh\utils\codim_mesh_data_set.h(95,47): message : could be 'std::shared_ptr<lf::mesh::utils::CodimMeshDataSet<double>> lf::mesh::utils::make_CodimMeshDataSet<double>(std::shared_ptr<const lf::mesh::Mesh>,lf::base::dim_t)' [C:\projects\lehrfempp\Build\projects\FisherKPP\splitting.vcxproj]
[00:14:59]        C:\projects\lehrfempp\lib\lf\mesh\utils\codim_mesh_data_set.h(113,38): message : or       'std::shared_ptr<lf::mesh::utils::CodimMeshDataSet<double>> lf::mesh::utils::make_CodimMeshDataSet<double>(const std::shared_ptr<const lf::mesh::Mesh> &,lf::base::dim_t)' [C:\projects\lehrfempp\Build\projects\FisherKPP\splitting.vcxproj]
~~~
and 
~~~

~~~

**Comment by hiptmair** [comment]
Absolutely no problems on my machine: both GCC and CLANG compile the code smoothly, and clang-tidy does not report any problems.

**Pull request merged**
