### PR TITLE
QuadO2

### PR DESCRIPTION
**Pull request by anianruoss**
- By @hiptmair's recommendation, `QuadO2` only uses 8 points.

- As you can see the `checkChildGeometryVolume` tests are failing. I checked that the refined local coordinates are calculated correctly. The volumes are close, but not within machine precision. The problem also can't be solved by using a higher order quadrature. Do you know how I can fix this?

```
Expected equality of these values:
  volume
    Which is: 68.448692
  refinedVolume
    Which is: 68.423599
Parent and children volumes differ for rp_regular
/home/travis/build/craffael/lehrfempp/lib/lf/geometry/test/geometry_tests.cc:252: Failure
Expected equality of these values:
  volume
    Which is: 68.448692
  refinedVolume
    Which is: 68.423599
Parent and children volumes differ for rp_barycentric
```

### CODE REVIEW

**Comment by hiptmair** [comment]
In the case of general quadrilateral the computation of the volume requires the integration of a _rational function_. In general, no quadrature rule of any order can return an "exact result" , thus. Thus, the unit test can merely verify that the computed volume is close to an expected value: `EXPECT_NEAR`.

**Comment by craffael** [comment]
> 
> 
> When using the positions of vertices and midpoints of edges to fix the shape of a `QuadO2`, omitting the center of gravity, one must use a hierarchical basis to encode the mapping from the reference square: Use the standard bilinear basis functions associated with the vertices plus the four bi-quadratic "bump functions" belonging to the midpoints of the edges. If one uses the standard nodal basis functions, the center of the unit square is always mapped to zero !

I'm a bit confused: If you use the O1 shape functions + O2 edge shape functions, the basis is not lagrangian anymore and the midpoints of the edges are not mapped to the specified points anymore? 
I think there are two options that we have:
1) Use 8-node Serendipity shape functions to construct the geometry mapping.
2) Use 9-node lagrangian shape functions to construct the geometry mapping.

Gmsh provides 9-node quadrilaterals so both options are possible... I think since we are only talking about geometry mappings the serendipity basis functions are an option? On the other hand, Lagrange shape functions are easier to analyze and allow for iso-parameteric finite elements... 
@hiptmair what do you prefer?

**Comment by hiptmair** [comment]
/scratch/users/ralfh/NOSAVE/numpde/Numcourses/NumPDE/lehrfempp/lib/lf/geometry/lf.geometry.pdf

**Comment by hiptmair** [comment]
Please see the formulas for the parametric mapping made explicit in the following notes:
[lf.geometry.pdf](https://github.com/craffael/lehrfempp/files/2717582/lf.geometry.pdf)
They show how to use 8 bi-quadratic basis functions for mapping the square to a `QuadO2`.

**Comment by anianruoss** [comment]
> Please see the formulas for the parametric mapping made explicit in the following notes:
> [lf.geometry.pdf](https://github.com/craffael/lehrfempp/files/2717582/lf.geometry.pdf)
> They show how to use 8 bi-quadratic basis functions for mapping the square to a `QuadO2`.

@hiptmair I am trying to implement your formulas for the bi-quadratic basis functions but I believe that they are wrong. For example, the point `[1/2, 0]` is not mapped to `m_0`. I will try to fix the formulas but I have a bad feeling that I will just recover the standard nodal basis functions.

**Comment by anianruoss** [comment]
@hiptmair I implemented the corrected version of the bi-quadratic basis functions but the tests still fail with the same error. In fact, your formulas are equivalent to the ones I had implemented in the first place. What should I do?

**Comment by hiptmair** [comment]
I have checked the formulas and they seem to be all right. 
[lf.geometry.pdf](https://github.com/craffael/lehrfempp/files/2813589/lf.geometry.pdf)
I will mull over these formulas some more; maybe I have missed something.

**Comment by anianruoss** [comment]
The way I interpret it `b_0 = 1/4*x*(1-x)*(1-y)` yields `b_0(1/2, 0) = 1/16` and not `1`. (The correct form being `b_0 = 4*x*(1-x)*y`).

However, as mentioned above, these formulas still produce the error with the volume mapping.

**Comment by craffael** [comment]
I think the prefactors of the `\beta` are wrong: `\beta_0 = 4*x*(1-x)*(1-y)`, i.e. It should be `4` and not `1/4`

**Comment by anianruoss** [comment]
Using [`numpy.polyfit`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.polyfit.html) with degree 2 I plotted a `QuadO2` from the global coordinates. Then I evaluated a couple of random points on the reference element.

quad02

I am not quite sure if `numpy.polyfit` is suited for this task but something clearly seems wrong. I will check my `Global` function again.

**Comment by anianruoss** [comment]
I re-implemented `Global()` as naively as possible (simple for-loop, no Eigen arrays, direct evaluation of the formulas presented in the document) and I get exactly the same point distribution. What really confuses me are the points below the lowest vertex. I don't mean to be rude but @hiptmair are you sure that it is possible to implement the parametric mapping for `QuadO2` with 8 points and these basis functions?

**Comment by hiptmair** [comment]
I apologize for the wrong 1/4, of course it should be 4. 
What you observe in your plot is a typical phenomenon affecting higher order interpolation: loss of monotonicity: the cardinal basis functions for the eight interpolation points will have rather large negative values in some points. Don't worry, if the distortion of the quadrilateral cells compared to the bilinear case is small, this effect will not be too severe. Of course, in case of large distortion, the Jacobian determinant will change sign and the parameterization will break down.

**Comment by anianruoss** [comment]
@hiptmair yes, you are right. I checked the determinant of the jacobian and the tests fail for large negative values. This is the new test `QuadO2`:

quad02

Thank you both for helping me debug this problem. Do you want to look at the code again or can I merge the pull request?

**Pull request merged**
