### PR TITLE
Investigate parametrization breakdown for second-order geometry objects

### PR DESCRIPTION
**Pull request by anianruoss**
@hiptmair I implemented a quick investigation into the parametrization of second-order geometry objects. Please have a look [here](https://github.com/craffael/lehrfempp/blob/visualize_parametrization_breakdown/examples/geometry/parametrization_breakdown/parametrization_breakdown.ipynb). The plots are also saved as `.png` files.

Let me know if:
- you want a `Python` script instead of a `Jupyter Notebook`
- you want to save the plots as vector-based images (e.g. `.eps`) for increased quality

### CODE REVIEW

**Comment by anianruoss** [comment]
> * Jupyter notebook is ok
> * I need the output as .eps, because this is the only graphics format I can import into the lecture document.
> * Concerning the sign of the Jacobian determinant, it would be a good idea to visualize the determinant as a function over the reference element. A color plot might do a good job: redish colors for posittive values, blueish colors for negative values. Then a change of sign becomes very conspicuous.

All done, let me know if you want me to change anything else.

**Comment by craffael** [comment]
Very nice!

**Comment by anianruoss** [comment]
@hiptmair I added the `README`s you requested. Let me know if I can merge this pull request.

**Comment by hiptmair** [comment]
Please go ahead and merge into "master".

**Pull request merged**
